- link:
    ~/.latexmkrc: confs/latexmkrc

- shell:
  - command: 'MYTEXMF=texmf/tex/latex ; [[ $(uname -s) = Darwin ]] && mkdir -p "$HOME/Library/$MYTEXMF" || [[ $(uname -s) = Linux ]] && mkdir -p "$HOME/$MYTEXMF"'
    description: Create latex personal directory

