- link:
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh:
      force: true
      path: meta/github/oh-my-zsh
    ~/.oh-my-zsh/custom/:
      glob: true
      force: true
      path: zsh/custom/*
    ~/.oh-my-zsh/custom/plugins/:
      glob: true
      force: true
      path: zsh/custom/plugins/*
    ~/.oh-my-zsh/custom/themes/:
      glob: true
      force: true
      path: zsh/custom/themes/*
      #- shell:
      #  -
      #    command: ln -s $HOME/Dotfiles/meta/github/oh-my-zsh $HOME/.oh-my-zsh
      #    stdout: true
      #  -
      #    command: ln -s $HOME/Dotfiles/zsh/custom/aliases.szh $HOME/.oh-my-zsh/custom/aliases.zsh
      #    stdout: true
      #  -
      #    command: ln -s $HOME/Dotfiles/zsh/custom/zshrc.szh $HOME/.oh-my-zsh/custom/zshrc.zsh
      #    stdout: true
