- link:
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh: zsh/oh-my-zsh
    ~/.oh-my-zsh/custom/:
      glob: true
      force: false
      path: zsh/custom/*
    ~/.oh-my-zsh/custom/plugins/:
      glob: true
      force: false
      path: zsh/custom/plugins/*
    ~/.oh-my-zsh/custom/themes/:
      glob: true
      force: false
      path: zsh/custom/themes/*
