- shell:
  -
    command: if [ ! -d ${HOME}/.config/aacs ]; then mkdir ${HOME}/.config/aacs; fi
    stdout: true
    stderr: true
    description: Testing directory

  -
    command: if [ ! -f ${HOME}/.config/aacs/KEYDB.cfg ]; then wget --no-check-certificate -O ${HOME}/.config/aacs/KEYDB.cfg http://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg; fi
    stdout: true
    stderr: true
    description: Downloading AACS db keys
