- shell:
  -
    command: '[[ ! -d ${HOME}/.config/aacs ]] && mkdir ${HOME}/.config/aacs'
    stdout: true
    stderr: true
    description: Testing directory

  -
    command: '[[ ! -f ${HOME}/.config/aacs/KEYDB.cfg ]] && /bin/bash -c "curl -fsSL http://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg -o ${HOME}/.config/aacs/KEYDB.cfg"'
    stdout: true
    stderr: true
    description: Downloading AACS db keys

