- link:
    ${HOME}/.mbsynrc:
      path: conf/mbsyncrc
    ${HOME}/.notmuch-config:
      path: conf/notmuch-config
    ${HOME}/.config/astroid:
      path: conf.d/astroid
    ${HOME}/.config/alot:
      path: conf.d/alot
    
