- link:
    ${HOME}/.config/nvim:
        path: conf.d/nvim
        relink: true

- shell:
    - command: '/bin/bash -c "$(which nvim) -es -u ${HOME}/.config/nvim/init.vim -i NONE -c PlugInstall -c qa || true"'
      stdout: true
      stdin: true
      stderre: true
      description: Installing Nvim plugins
