- shell:
  -
    command: echo "This is a test file. If you are reading this, it is that everything is ok." > /tmp/dotbot_test_file
    stdin: false
    stdout: false
    description: Create a test file.
    quiet: true
  -
    command: cat /tmp/dotbot_test_file
    stdin: false
    stdout: true
    description: Read the test file.
    quiet: true
  -
    command: rm /tmp/dotbot_test_file
    stdin: false
    stdout: false
    description: Delete the test file.
    quiet: true

- if:
  - cond: "test $(distro -j | jq .id | grep manjaro)"
    met:
      - shell:
        - echo "Using Manjaro"
    unmet:
      - shell:
        - echo "Not using Manjaro"
