#!/bin/bash
# File              : post-new
# Author            : Jeff LANCE <email@jefflance.me>
# Date              : 10.02.2015
# Last Modified Date: 01.03.2021
# Last Modified By  : Jeff LANCE <email@jefflance.me>


#
MAILCLIENT_BIN=$(which aerc)
NOTMUCH_BIN=$(which notmuch)
NOTIFY_BIN=$(which notify-send)


function notify() {
  # count new mails and display a message
  newcount=$(${NOTMUCH_BIN} count tag:new)
  summary="Tu as reçu ${newcount} message"

  # come on, who here doesn't actually hate "you have 1 new message(s)"?
  if [ $newcount -gt 1 ]; then
    summary="${summary}s"
  fi

  if [ $newcount -gt 0 ]; then
    detail="$(${NOTMUCH_BIN} search --output=summary --format=json tag:new \
      | sed -e 's/.*authors": "//;s/|[^"]*"/"/;s/", "subject": "/ : /;s/".*//')"
  fi

  if [ ${newcount} -gt 0 ]; then
    ${NOTIFY_BIN} \
      -i /usr/share/notify-osd/icons/hicolor/scalable/status/notification-message-email.svg \
      -c Mail "${summary}." "${detail}" -t 10000
  fi
}

# some additional tags
${NOTMUCH_BIN} tag --input=${HOME}/Mail/.notmuch/tagupdate


if [ "x${DISPLAY}" != "x" ]; then
  logger -t notmuch "post-new: notify"
  notify
fi


# run afew on mew mails and make moves
# afew --tag --new
# afew --move-mails

exit 0


# vim:ft=sh
