#!/bin/bash
# File              : pre-new
# Author            : Jeff LANCE <email@jefflance.me>
# Date              : 04.05.2020
# Last Modified Date: 01.03.2021
# Last Modified By  : Jeff LANCE <email@jefflance.me>


ASTROID_BIN=$(which astroid)


# purging trash
notmuch search --output=files --format=text0 \
  -- tag:deleted date:...7d | xargs -0 --no-run-if-empty rm


exit 0


# vim:ft=sh
