- defaults:
    link:
      create: true
      relink: true
    conditional:
      isolated: false

- shell:
    - [
      git submodule update --init --recursive, "Installing submodules."
    ]

- clean: [
    '~',
    '~/.config'
    ]


