- defaults:
    link:
      create: true
      relink: true

- shell:
    - [
    git submodule update --init --recursive, "Installing submodules.",
    ]

- clean: [
    '~',
    '~/.config',
    ]

- conditional:
    if: 'command -v pamac'
    then:
        shell:
        - pamac install yay

