- defaults:
    link:
      create: true
      relink: true

- shell:
    - [
    git submodule update --init --recursive, "Installing submodules."
    ]

- clean: [
    '~',
    '~/.config'
    ]


- defaults:
    conditional:
        isolated: False

- conditional:
    if:
        tty:
    then:
        shell:
        - command: "echo oui"

