# Start configuration added by Zim install {{{
#
# User configuration sourced by all invocations of the shell
#

# Define Zim location
: ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}
# }}} End configuration added by Zim install

# >>> define PATH variable as an array
typeset -U path
# <<< define PATH variable as an array

# >>> set PATH so it includes user's private bin if it exists >>>
path=(~/bin ~/.local/bin $path[@])
# <<< set PATH so it includes user's private bin if it exists <<<

# >>> environment variables >>>
export BROWSER=qutebrowser
export EDITOR=$([[ $(command -v lvim) ]] && echo lvim || echo vim)
export TERMINAL=alacritty
# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
export MYVIMRC="${HOME}/.vimrc"
export PASSWORD_STORE_DIR="${HOME}/Private/.password-store"
export PASSWORD_STORE_ENABLE_EXTENSIONS=True
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
export ZK_NOTEBOOK_DIR="${HOME}/Notes"
export OPENAI_API_KEY="$(pass _api_keys/openai_perso-1)"
export IPINFO_API_KEY="$(pass _api_keys/ipinfo_perso-0)"
# <<< environment variables <<<

# }}} End personnal configuration directives

