#!/bin/bash
# File              : purge_trash
# Author            : Jeff LANCE <email@jefflance.me>
# Date              : 10.02.2015
# Last Modified Date: 04.05.2020
# Last Modified By  : Jeff LANCE <email@jefflance.me>

echo "[ASTROID]: start $(basename $0)"

notmuch search --output=files --format=text0 \
  -- tag:deleted folder:"/trash/" \
  | xargs -0 --no-run-if-empty rm 
  
notmuch new
mbsync -a

echo "[ASTROID]: end $(basename $0)"


# vim:ft=sh
