#!/usr/bin/env bash
#
# get a tag as first argument and message id as second argument
#

# check if the message matches the tag
if [[ $(notmuch search id:$2 and tag:$1) ]]; then
  echo "removing tag: $1 from id:$2"
  # remove the tag
  notmuch tag -$1 id:$2
else
  echo "adding tag: $1 to id:$2"
  # add the tag
  notmuch tag +$1 id:$2
fi
