#!/usr/bin/env bash
#
# get a tag as first argument and thread id as second argument
#

# check if the thread matches the tag
if [[ $(notmuch search thread:$2 and tag:$1) ]]; then
  echo "removing tag: $1 from thread:$2"
  # remove the tag
  notmuch tag -$1 thread:$2
else
  echo "adding tag: $1 to thread:$2"
  # add the tag
  notmuch tag +$1 thread:$2
fi
