typeset -U path

# set PATH so it includes user's private bin if it exists
path=(~/bin ~/.local/bin $path[@])

# Active gnome-keyring
if [ -n "${DESKTOP_SESSION}" ];then
   eval $(gnome-keyring-daemon --start)
   export SSH_AUTH_SOCK
fi

# set PATH so it includes miniconda bin dir if it exists
path=(~/miniconda3/bin $path[@])

# environment variables
export EDITOR=nano
