typeset -U path

# set PATH so it includes user's private bin if it exists
path=(~/bin ~/.local/bin $path[@])

# Active gnome-keyring
if [ -n "${DESKTOP_SESSION}" ];then
   eval $(gnome-keyring-daemon --start)
   export SSH_AUTH_SOCK
fi

# set PATH so it includes miniconda bin dir if it exists
#path=(~/miniconda3/bin $path[@])

# set PATH for nvm
export NVM_DIR="$HOME/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# environment variables
export EDITOR=vim
export XDG_CURRENT_DESKTOP=
export DESKTOP_SESSION=
#export XDG_DATA_DIRS="/home/jeff/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
